### ISSUE TITLE
Transfer to datalib?

### ISSUE THREAD

**Issue by eugene-eeo** [datalib/proclib#1]
@rodricios, this library can be transferred to the datalib organisation, here's why: if I'm not mistaken some data extraction requires the use of high-performance text transformation (search and replace, etc) tools. What this library hopes to do is allow Python to be easily used as a declarative layer, for configuring/writing the extraction algorithm, then delegating the harder (in terms of clock cycles) work of post-processing text to the Unix commands.

**Comment by rodricios** [comment]
I love this library! Let's please transfer this.
