### ISSUE TITLE
SignalsDB Integration

### ISSUE THREAD

**Issue by eugene-eeo** [datalib/proclib#2]
@rodricios do you think that this module should integrate and possibly depend on SignalsDB? Currently there is no way to "explain" the signals that caused the process to exit in the `Response` class, and adding it would seem like a good idea REPL wise but I don't know how good an idea it would be in production. Personally I find myself sometimes looking to Unix manuals to look up the name of the signal (which is why SignalsDB was made a long time ago, I've only recently uploaded the code) but I don't know about others. We could also have a light dependency:

``` python
try:
    from signalsdb.api import explain
    SIGNALDB_AVAILABLE = True
except ImportError:
    SIGNALDB_AVAILABLE = False
```

But that seems a little polluting and hack-ish to me. What's your 0.5 `$currency`?

**Comment by rodricios** [comment]
I think that it might be better to include just for the sake of the user.
He or she may likely want to know more than know less by default.

**Comment by rodricios** [comment]
Another reason for why you may want to integrate signalsdb into proclib is
that proclib is maintained by you! I'm actually removing the dependency
from chardet in the new rearchitecture of libextract.

Gotta warn you though, it may look like a completely different beast:

https://github.com/datalib/libextract/tree/new-architecture
